version: 1

update_configs:
- package_manager: "dotnet:nuget"
  directory: "/src/UnMango.Http"
  update_schedule: "live"
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "semver:patch"
  default_assignees:
  - "UnstoppableMango"

- package_manager: "dotnet:nuget"
  directory: "/test/UnMango.Http.Tests"
  update_schedule: "live"
  automerged_updates:
  - match:
      dependency_type: "all"
      update_type: "semver:patch"
  default_assignees:
  - "UnstoppableMango"
